// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Build struct {
	ID          int64
	CreatedAt   time.Time
	CompletedAt sql.NullTime
	ExitCode    sql.NullInt64
	Command     string
}
